import * as fs from 'fs';
import * as path from 'path';

/**
 * Synchronizes contracts from JSON schema to Zod.
 */
async function syncContracts() {
  let jsonSchemaToZod;
  try {
    const module = await import('json-schema-to-zod');
    jsonSchemaToZod = module.jsonSchemaToZod;
  } catch (err: unknown) {
    const error = err as { code?: string; message?: string };
    if (error.code === 'ERR_MODULE_NOT_FOUND' || error.message?.includes('Cannot find package')) {
      console.error('❌ Error: json-schema-to-zod not found.');
      console.error('   Please run `pnpm install` in the root directory.');
      process.exit(1);
    }
    throw err;
  }

  let schemaPath = path.join(process.cwd(), 'cli/dev_tools/cli-schema.json');
  let outputPath = path.join(process.cwd(), 'mcp/src/tools/contract.ts');

  if (!fs.existsSync(schemaPath)) {
    // Try relative to package root if in extracted mode (run from root)
    schemaPath = path.join(process.cwd(), 'cli/dev_tools/cli-schema.json');
    outputPath = path.join(process.cwd(), 'mcp/src/tools/contract.ts');
  }

  if (!fs.existsSync(schemaPath)) {
    // Try if run from mcp directory
    schemaPath = path.join(process.cwd(), '../cli/dev_tools/cli-schema.json');
    outputPath = path.join(process.cwd(), 'src/tools/contract.ts');
  }

  if (!fs.existsSync(schemaPath)) {
    console.error(`Schema not found at ${schemaPath}`);
    process.exit(1);
  }

  const rawSchema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8')) as { models?: Record<string, unknown> };
  const models = rawSchema.models || {};

  let tsContent = `// Automatically generated by sync-contracts.ts. Do not edit manually.\n`;
  tsContent += `import { z } from "zod";\n\n`;

  for (const [name, schema] of Object.entries(models)) {
    // Get the raw Zod expression without any variable assignment or imports
    const zodExpression = jsonSchemaToZod(schema as any, { module: 'none' });

    tsContent += `export const ${name}Schema = ${zodExpression};\n\n`;
    tsContent += `export type ${name} = z.infer<typeof ${name}Schema>;\n\n`;

    // Also export the raw JSON schema for MCP definitions
    tsContent += `export const ${name}JsonSchema = ${JSON.stringify(schema, null, 2)} as const;\n\n`;
  }

  // Normalize newlines to \n and ensure exactly one trailing newline at EOF
  const finalContent = tsContent.replace(/\r\n/g, '\n').trimEnd() + '\n';

  fs.writeFileSync(outputPath, finalContent);
  console.log(`Generated ${outputPath}`);
}

// Ensure execution is awaited and errors are caught
(async () => {
  try {
    await syncContracts();
  } catch (err) {
    console.error('❌ Unexpected error during contract synchronization:', err);
    process.exit(1);
  }
})();
